apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Chart.Name }}
    chart: {{ template "chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        timestamp: "{{ date "20060102150405" now }}"
      labels:
        app: {{ .Chart.Name }}
        release: {{ .Release.Name }}
        repository: {{ .Release.Name }}-local
        imageTag: latest
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "ocelot-local:latest"
          command: ["http-server", "./dist", "-p", "80"]
          volumeMounts:
            - name: src
              mountPath: /usr/src/app
          imagePullPolicy: IfNotPresent
          env: []
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
            - name: althttp
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /index.html
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 10
          resources: {}
        {{- if .Values.watch }}
        - name: {{ .Chart.Name }}-watch
          image: "ocelot-local:latest"
          command: ["make", "watch", "BOWER_ARGS=--allow-root"]
          volumeMounts:
            - name: src
              mountPath: /usr/src/app
          imagePullPolicy: IfNotPresent
          env: []
        {{- end }}
      volumes:
        - name: src
          hostPath:
            type: Directory
            path: {{ .Values.persistence.path }}
      tolerations: []
